"""
fear_output_reader.py
=====================
Extracts time-history of mass loss and frontal area loss from FEAR out_*.dat
output files (Tecplot fepoint ASCII format).

Variables in out_*.dat: x, y, z, Mgx, Mgy, p, U, V, T
Element type: quadrilateral (2D axisymmetric cross-section)

The FEAR mesh is a 2D axisymmetric slice.  Frontal area is computed as the
axisymmetric surface area generated by revolving the surface line elements
(BC 4 nodes) around the axis of symmetry (x-axis).

Mass loss is estimated as:
  PICA_density × ΔVolume
where ΔVolume = integral of (recession depth × 2π × y) ds along the surface.

Output: time-history CSV sampled every ~output_time_interval seconds.

Usage (standalone):
  python fear_output_reader.py \\
      --fear-dir   runs/case_000/fear_outputs \\
      --output     training_data/case_000_history.csv \\
      --config     pipeline_config.yaml
"""

import argparse
import csv
import math
import re
from pathlib import Path

import numpy as np
import yaml


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def extract_time_history(fear_dir: Path, output_csv: Path,
                         config: dict) -> list[dict]:
    """
    Parse FEAR out_*.dat files and write a time-history CSV.

    Parameters
    ----------
    fear_dir : Path
        Directory containing out_001.dat … out_N.dat (FEAR output).
    output_csv : Path
        Destination CSV path.
    config : dict
        Parsed pipeline_config.yaml.

    Returns
    -------
    list[dict]
        Time-history rows written to the CSV.
    """
    fear_cfg  = config.get("fear", {})
    dt        = float(fear_cfg.get("fear_timestep", 0.06))        # s per file index
    interval  = float(fear_cfg.get("output_time_interval", 5.0))  # s between samples
    rho_pica  = float(fear_cfg.get("pica_density", 1600.0))       # kg/m³

    # Files stride: how many out_*.dat files correspond to one interval
    stride = max(1, round(interval / dt))

    # Collect and sort out_*.dat files
    dat_files = sorted(fear_dir.glob("out_*.dat"),
                       key=lambda p: _parse_index(p.name))
    if not dat_files:
        raise FileNotFoundError(f"No out_*.dat files found in {fear_dir}")

    print(f"[FEAR reader] Found {len(dat_files)} timestep files in {fear_dir}")
    print(f"[FEAR reader] Sampling every {stride} files (~{interval} s intervals)")

    # ── Parse initial geometry (t=0) ────────────────────────────────────────
    nodes0, elements0, bc4_node_ids = _parse_dat_file(dat_files[0])
    if not bc4_node_ids:
        # Fallback: infer surface nodes as those with y > 0 and x near the front face
        bc4_node_ids = _infer_surface_nodes(nodes0)
        print(f"[FEAR reader] WARNING: Could not identify BC 4 nodes from file. "
              f"Inferred {len(bc4_node_ids)} surface nodes by geometry.")

    area0, surf_nodes0 = _compute_surface_area(nodes0, elements0, bc4_node_ids)
    stag_node_id       = _find_stagnation_node(nodes0, bc4_node_ids)
    print(f"[FEAR reader] Initial frontal area = {area0:.6f} m²  "
          f"| Stagnation node id = {stag_node_id}")

    # ── Sample selected timesteps ────────────────────────────────────────────
    selected = [dat_files[0]]  # always include t=0
    for i in range(stride, len(dat_files), stride):
        selected.append(dat_files[i])
    if dat_files[-1] not in selected:
        selected.append(dat_files[-1])   # always include final timestep

    rows = []
    for dat_file in selected:
        idx   = _parse_index(dat_file.name)
        t_sim = idx * dt  # simulation time for this file

        nodes_t, elements_t, _ = _parse_dat_file(dat_file)

        area_t, surf_nodes_t  = _compute_surface_area(nodes_t, elements_t, bc4_node_ids)
        area_loss             = max(0.0, area0 - area_t)

        # Recession depth at stagnation point (displacement along x-axis)
        stag_recession_m = _stagnation_recession(nodes0, nodes_t, stag_node_id)

        # Mass loss estimate: rho_PICA × ΔVolume
        # ΔVolume = axisymmetric integral of (recession_depth × 2π y) ds
        delta_vol  = _volume_change(nodes0, nodes_t, elements0, bc4_node_ids)
        mass_loss  = rho_pica * delta_vol

        rows.append({
            "time_s":               round(t_sim, 4),
            "frontal_area_m2":      round(area_t,   8),
            "frontal_area_loss_m2": round(area_loss, 8),
            "mass_loss_kg":         round(mass_loss, 8),
            "stag_recession_mm":    round(stag_recession_m * 1000, 6),
        })

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    _write_csv(rows, output_csv)
    print(f"[FEAR reader] Time history ({len(rows)} points) → {output_csv}")
    return rows


def get_summary(rows: list[dict]) -> dict:
    """Return scalar summary from a time-history row list."""
    if not rows:
        return {}
    return {
        "total_mass_loss_kg":         rows[-1]["mass_loss_kg"],
        "total_frontal_area_loss_m2": rows[-1]["frontal_area_loss_m2"],
        "max_stag_recession_mm":      max(r["stag_recession_mm"] for r in rows),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Tecplot fepoint parser
# ─────────────────────────────────────────────────────────────────────────────

def _parse_dat_file(dat_path: Path):
    """
    Parse a single FEAR out_*.dat Tecplot ASCII file.

    Returns
    -------
    nodes : dict[int, np.ndarray]
        node_id → [x, y, z]  (1-based Tecplot node numbering)
    elements : list[list[int]]
        Each element is a list of 4 node IDs (quadrilateral connectivity).
    bc4_node_ids : set[int]
        Node IDs identified as being on the BC 4 (front surface) — derived
        from element connectivity inspection.
    """
    nodes    = {}
    elements = []
    n_nodes  = 0
    n_elems  = 0

    with open(dat_path) as f:
        lines = f.readlines()

    # Find zone header to get n, e
    for line in lines:
        m = re.search(r'n\s*=\s*(\d+)', line, re.IGNORECASE)
        if m:
            n_nodes = int(m.group(1))
        m2 = re.search(r'e\s*=\s*(\d+)', line, re.IGNORECASE)
        if m2:
            n_elems = int(m2.group(1))
        if n_nodes and n_elems:
            break

    if n_nodes == 0:
        raise ValueError(f"Could not parse node count from {dat_path}")

    # Read data lines (after header comments/zone line)
    data_lines = []
    in_data = False
    for line in lines:
        stripped = line.strip()
        if stripped.lower().startswith("zone"):
            in_data = True
            continue
        if in_data and stripped and not stripped.startswith("*"):
            data_lines.append(stripped)

    # First n_nodes lines → node data [x, y, z, Mgx, Mgy, p, U, V, T]
    for i in range(min(n_nodes, len(data_lines))):
        vals = data_lines[i].split()
        if len(vals) >= 3:
            x, y, z = float(vals[0]), float(vals[1]), float(vals[2])
            nodes[i + 1] = np.array([x, y, z])

    # Next n_elems lines → element connectivity (4 node IDs per quad)
    for i in range(n_elems):
        idx = n_nodes + i
        if idx < len(data_lines):
            ids = [int(v) for v in data_lines[idx].split()]
            if len(ids) >= 4:
                elements.append(ids[:4])

    # Identify BC 4 (front surface) nodes: nodes appearing in elements
    # whose y-coordinate is at the maximum (outermost surface in 2D slice)
    bc4_node_ids = _identify_surface_nodes(nodes, elements)

    return nodes, elements, bc4_node_ids


def _identify_surface_nodes(nodes: dict, elements: list) -> set:
    """
    Identify surface (BC 4 / front face) nodes.

    In the 2D Gmsh mesh, the ablating front surface corresponds to the
    elements at the maximum x-extent (nose + cone). We identify boundary
    edges (edges belonging to only one element) on the high-x side.
    """
    if not nodes:
        return set()

    # Find all edges; boundary edges appear exactly once
    from collections import Counter
    edge_count = Counter()
    elem_by_edge = {}
    for elem in elements:
        for j in range(4):
            e = tuple(sorted([elem[j], elem[(j + 1) % 4]]))
            edge_count[e] += 1
            elem_by_edge[e] = elem

    boundary_nodes = set()
    for edge, count in edge_count.items():
        if count == 1:
            boundary_nodes.update(edge)

    # Filter to only the front-facing surface (max x side — ablating surface)
    if not boundary_nodes:
        return boundary_nodes

    x_vals = np.array([nodes[n][0] for n in boundary_nodes if n in nodes])
    if len(x_vals) == 0:
        return boundary_nodes

    x_max  = x_vals.max()
    x_min  = x_vals.min()
    # Front surface is near maximum x
    threshold = x_min + 0.7 * (x_max - x_min)
    surface_nodes = {n for n in boundary_nodes
                     if n in nodes and nodes[n][0] >= threshold}

    return surface_nodes if surface_nodes else boundary_nodes


def _infer_surface_nodes(nodes: dict) -> set:
    """Fallback: return nodes near the maximum x boundary."""
    if not nodes:
        return set()
    xs = np.array([v[0] for v in nodes.values()])
    x_threshold = xs.max() - 0.1 * (xs.max() - xs.min())
    return {nid for nid, pos in nodes.items() if pos[0] >= x_threshold}


# ─────────────────────────────────────────────────────────────────────────────
# Geometry calculations
# ─────────────────────────────────────────────────────────────────────────────

def _compute_surface_area(nodes: dict, elements: list,
                          bc4_node_ids: set) -> tuple[float, list]:
    """
    Compute axisymmetric frontal area by revolving the surface line segments
    around the x-axis (symmetry axis).

    A = 2π ∫ y ds  (Pappus's centroid theorem for surface of revolution)

    Returns (area_m2, sorted_surface_node_positions).
    """
    if not bc4_node_ids:
        return 0.0, []

    # Build ordered list of surface nodes sorted by x-coordinate
    surf_positions = sorted(
        [(nid, nodes[nid]) for nid in bc4_node_ids if nid in nodes],
        key=lambda t: t[1][0]
    )

    area = 0.0
    for i in range(len(surf_positions) - 1):
        _, p1 = surf_positions[i]
        _, p2 = surf_positions[i + 1]
        y_avg = 0.5 * (p1[1] + p2[1])
        ds    = math.sqrt((p2[0] - p1[0])**2 + (p2[1] - p1[1])**2)
        area += 2 * math.pi * y_avg * ds

    return area, surf_positions


def _stagnation_recession(nodes0: dict, nodes_t: dict, stag_id: int) -> float:
    """Return x-displacement of the stagnation node (positive = recession inward)."""
    if stag_id not in nodes0 or stag_id not in nodes_t:
        return 0.0
    dx = nodes0[stag_id][0] - nodes_t[stag_id][0]  # initial x − current x
    return max(0.0, dx)


def _volume_change(nodes0: dict, nodes_t: dict,
                   elements: list, bc4_node_ids: set) -> float:
    """
    Estimate volume change (m³) from surface node recession.

    Uses axisymmetric approximation:
      dV = 2π × y_avg × recession_depth × ds
    for each segment of the ablating surface.
    """
    surf_nodes = sorted(
        [(nid, nodes0[nid]) for nid in bc4_node_ids if nid in nodes0],
        key=lambda t: t[1][0]
    )

    delta_vol = 0.0
    for i in range(len(surf_nodes) - 1):
        nid1, p1_0 = surf_nodes[i]
        nid2, p2_0 = surf_nodes[i + 1]

        # Recession depth at each node (x displacement)
        rec1 = max(0.0, p1_0[0] - nodes_t.get(nid1, p1_0)[0])
        rec2 = max(0.0, p2_0[0] - nodes_t.get(nid2, p2_0)[0])
        rec_avg = 0.5 * (rec1 + rec2)

        y_avg = 0.5 * (p1_0[1] + p2_0[1])
        ds    = math.sqrt((p2_0[0] - p1_0[0])**2 + (p2_0[1] - p1_0[1])**2)

        delta_vol += 2 * math.pi * y_avg * rec_avg * ds

    return max(0.0, delta_vol)


def _find_stagnation_node(nodes: dict, bc4_node_ids: set) -> int:
    """Return the node ID closest to the stagnation point (x=0, y=0)."""
    if not bc4_node_ids:
        return next(iter(nodes)) if nodes else 0
    return min(bc4_node_ids,
               key=lambda nid: math.sqrt(nodes[nid][0]**2 + nodes[nid][1]**2)
               if nid in nodes else float('inf'))


def _parse_index(filename: str) -> int:
    """Extract integer index from 'out_001.dat' → 1."""
    m = re.search(r'out_(\d+)', filename)
    return int(m.group(1)) if m else 0


# ─────────────────────────────────────────────────────────────────────────────
# Output
# ─────────────────────────────────────────────────────────────────────────────

def _write_csv(rows: list[dict], out_path: Path) -> None:
    if not rows:
        return
    with open(out_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


# ─────────────────────────────────────────────────────────────────────────────
# CLI entry point
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Extract FEAR time-history of mass loss and frontal area")
    parser.add_argument("--fear-dir", required=True,
                        help="Directory containing out_*.dat FEAR output files")
    parser.add_argument("--output",   required=True,
                        help="Output CSV path for time history")
    parser.add_argument("--config",   default="pipeline_config.yaml")
    args = parser.parse_args()

    with open(args.config) as f:
        config = yaml.safe_load(f)

    extract_time_history(
        fear_dir=Path(args.fear_dir),
        output_csv=Path(args.output),
        config=config,
    )


if __name__ == "__main__":
    main()
